### ISSUE TITLE
[Bug]: Stream.connect() failing 

### ISSUE THREAD

**Issue by akaushik1998** [blocknative/python-sdk#18]
### Current Behavior

Getting the following error when running this program (modified off this: https://gist.github.com/jac18281828/47a650e2525aa23a2b0039236fb29e6b#file-confirm_n-py). The program sometimes works and sometimes fails with the following error. Not clear what causes it to work/fail. 

![Screen Shot 2021-11-16 at 10 19 53 PM](https://user-images.githubusercontent.com/61363904/142134114-117f608d-5760-4be7-977a-e1c6be75c088.png)

2021-11-17T04:09:16.120771129Z API Failed: 'in <string>' requires string as left operand, not ErrorReason
2021-11-17T04:09:16.143041254Z Traceback (most recent call last):
2021-11-17T04:09:16.143312129Z   File "/workspaces/subscribe/scratch.py", line 31, in <module>
2021-11-17T04:09:16.143328754Z     stream.connect()
2021-11-17T04:09:16.143382338Z   File "/usr/local/lib/python3.9/dist-packages/blocknative/stream.py", line 162, in connect
2021-11-17T04:09:16.143411254Z     return trio.run(self._connect, base_url)
2021-11-17T04:09:16.143416338Z   File "/usr/local/lib/python3.9/dist-packages/trio/_core/_run.py", line 1932, in run
2021-11-17T04:09:16.143421213Z     raise runner.main_task_outcome.error
2021-11-17T04:09:16.143425629Z   File "/usr/local/lib/python3.9/dist-packages/blocknative/stream.py", line 318, in _connect
2021-11-17T04:09:16.143430504Z     await self._handle_connection(base_url)
2021-11-17T04:09:16.143434879Z   File "/usr/local/lib/python3.9/dist-packages/blocknative/stream.py", line 308, in _handle_connection
2021-11-17T04:09:16.143440379Z     nursery.start_soon(self._message_dispatcher)
2021-11-17T04:09:16.143444713Z   File "/usr/local/lib/python3.9/dist-packages/trio/_core/_run.py", line 815, in __aexit__
2021-11-17T04:09:16.143449671Z     raise combined_error_from_nursery
2021-11-17T04:09:16.143454421Z   File "/usr/local/lib/python3.9/dist-packages/blocknative/stream.py", line 202, in _poll_messages
2021-11-17T04:09:16.143459546Z     await self._message_handler(json.loads(msg))
2021-11-17T04:09:16.143463796Z   File "/usr/local/lib/python3.9/dist-packages/blocknative/stream.py", line 219, in _message_handler
2021-11-17T04:09:16.143468296Z     raise_error_on_status(message)
2021-11-17T04:09:16.143472421Z   File "/usr/local/lib/python3.9/dist-packages/blocknative/utils.py", line 52, in raise_error_on_status
2021-11-17T04:09:16.143477254Z     elif ErrorReason.EVENT_RATE_LIMIT in reason:
2021-11-17T04:09:16.143481796Z TypeError: 'in <string>' requires string as left operand, not ErrorReason
2021-11-17T04:09:16.143492004Z 
2021-11-17T04:09:16.143496588Z During handling of the above exception, another exception occurred:
2021-11-17T04:09:16.143501421Z 
2021-11-17T04:09:16.143505546Z Traceback (most recent call last):
2021-11-17T04:09:16.143509796Z   File "/workspaces/subscribe/scratch.py", line 35, in <module>
2021-11-17T04:09:16.143514296Z     traceback.print_exc(e)
2021-11-17T04:09:16.143518504Z   File "/usr/lib/python3.9/traceback.py", line 163, in print_exc
2021-11-17T04:09:16.143523254Z     print_exception(*sys.exc_info(), limit=limit, file=file, chain=chain)
2021-11-17T04:09:16.143528004Z   File "/usr/lib/python3.9/traceback.py", line 103, in print_exception
2021-11-17T04:09:16.143532338Z     for line in TracebackException(
2021-11-17T04:09:16.143536588Z   File "/usr/local/lib/python3.9/dist-packages/trio/_core/_multierror.py", line 393, in traceback_exception_init
2021-11-17T04:09:16.143541088Z     traceback_exception_original_init(
2021-11-17T04:09:16.143545171Z   File "/usr/lib/python3.9/traceback.py", line 508, in __init__
2021-11-17T04:09:16.143549629Z     self.stack = StackSummary.extract(
2021-11-17T04:09:16.143553796Z   File "/usr/lib/python3.9/traceback.py", line 340, in extract
2021-11-17T04:09:16.143564338Z     if limit >= 0:
2021-11-17T04:09:16.143568796Z TypeError: '>=' not supported between instances of 'TypeError' and 'int'

### Python Version

3.9

### Relevant log output

```shell
2021-11-17T04:09:16.120771129Z API Failed: 'in ' requires string as left operand, not ErrorReason
2021-11-17T04:09:16.143041254Z Traceback (most recent call last):
2021-11-17T04:09:16.143312129Z File "/workspaces/subscribe/scratch.py", line 31, in
2021-11-17T04:09:16.143328754Z stream.connect()
2021-11-17T04:09:16.143382338Z File "/usr/local/lib/python3.9/dist-packages/blocknative/stream.py", line 162, in connect
2021-11-17T04:09:16.143411254Z return trio.run(self._connect, base_url)
2021-11-17T04:09:16.143416338Z File "/usr/local/lib/python3.9/dist-packages/trio/_core/_run.py", line 1932, in run
2021-11-17T04:09:16.143421213Z raise runner.main_task_outcome.error
2021-11-17T04:09:16.143425629Z File "/usr/local/lib/python3.9/dist-packages/blocknative/stream.py", line 318, in _connect
2021-11-17T04:09:16.143430504Z await self._handle_connection(base_url)
2021-11-17T04:09:16.143434879Z File "/usr/local/lib/python3.9/dist-packages/blocknative/stream.py", line 308, in _handle_connection
2021-11-17T04:09:16.143440379Z nursery.start_soon(self._message_dispatcher)
2021-11-17T04:09:16.143444713Z File "/usr/local/lib/python3.9/dist-packages/trio/_core/_run.py", line 815, in aexit
2021-11-17T04:09:16.143449671Z raise combined_error_from_nursery
2021-11-17T04:09:16.143454421Z File "/usr/local/lib/python3.9/dist-packages/blocknative/stream.py", line 202, in _poll_messages
2021-11-17T04:09:16.143459546Z await self._message_handler(json.loads(msg))
2021-11-17T04:09:16.143463796Z File "/usr/local/lib/python3.9/dist-packages/blocknative/stream.py", line 219, in _message_handler
2021-11-17T04:09:16.143468296Z raise_error_on_status(message)
2021-11-17T04:09:16.143472421Z File "/usr/local/lib/python3.9/dist-packages/blocknative/utils.py", line 52, in raise_error_on_status
2021-11-17T04:09:16.143477254Z elif ErrorReason.EVENT_RATE_LIMIT in reason:
2021-11-17T04:09:16.143481796Z TypeError: 'in ' requires string as left operand, not ErrorReason
2021-11-17T04:09:16.143492004Z
2021-11-17T04:09:16.143496588Z During handling of the above exception, another exception occurred:
2021-11-17T04:09:16.143501421Z
2021-11-17T04:09:16.143505546Z Traceback (most recent call last):
2021-11-17T04:09:16.143509796Z File "/workspaces/subscribe/scratch.py", line 35, in
2021-11-17T04:09:16.143514296Z traceback.print_exc(e)
2021-11-17T04:09:16.143518504Z File "/usr/lib/python3.9/traceback.py", line 163, in print_exc
2021-11-17T04:09:16.143523254Z print_exception(*sys.exc_info(), limit=limit, file=file, chain=chain)
2021-11-17T04:09:16.143528004Z File "/usr/lib/python3.9/traceback.py", line 103, in print_exception
2021-11-17T04:09:16.143532338Z for line in TracebackException(
2021-11-17T04:09:16.143536588Z File "/usr/local/lib/python3.9/dist-packages/trio/_core/_multierror.py", line 393, in traceback_exception_init
2021-11-17T04:09:16.143541088Z traceback_exception_original_init(
2021-11-17T04:09:16.143545171Z File "/usr/lib/python3.9/traceback.py", line 508, in init
2021-11-17T04:09:16.143549629Z self.stack = StackSummary.extract(
2021-11-17T04:09:16.143553796Z File "/usr/lib/python3.9/traceback.py", line 340, in extract
2021-11-17T04:09:16.143564338Z if limit >= 0:
2021-11-17T04:09:16.143568796Z TypeError: '>=' not supported between instances of 'TypeError' and 'int'
```

**Comment by jac18281828** [comment]
Thanks for the report.  I'll take a look.   It appears the exception is being thrown while handling an error and therefore masking the reason.   

There are only three errors that could cause this particular exception.  Event rate limit, simulated rate limit or an unknown cause.   I suspect you are seeing a rate limit for your api key.

**Comment by jac18281828** [comment]
This should be resolved in the latest release.  Thanks again for the problem report!
