### ISSUE TITLE
[Bug]: trio\_timeouts.py", line 108, in fail_at     raise TooSlowError trio.TooSlowError

### ISSUE THREAD

**Issue by asafd11** [blocknative/python-sdk#39]
### Current Behavior

am opening threads for each project i want to subscribe to with different filters to each one 
when runing one seem to be ok but it throws exp when i am adding more 
\trio_timeouts.py", line 108, in fail_at
    raise TooSlowError
trio.TooSlowError
anyone run in to this error to slow?

```
Exception in thread Thread-11 (master_the_pool):
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "c:\NFT\revealBot\txpool_master.py", line 107, in master_the_pool
    stream.connect()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\blocknative\stream.py", line 165, in connect
    return trio.run(self._connect, base_url)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\trio\_core\_run.py", line 1932, in run
    raise runner.main_task_outcome.error
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\blocknative\stream.py", line 320, in _connect
    async with open_websocket_url(base_url) as ws:
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\async_generator\_util.py", line 53, in __aexit__
    await self._agen.athrow(type, value, traceback)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\async_generator\_impl.py", line 366, in step
    return await ANextIter(self._it, start_fn, *args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\async_generator\_impl.py", line 202, in send
    return self._invoke(self._it.send, value)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\async_generator\_impl.py", line 209, in _invoke
    result = fn(*args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\trio_websocket\_impl.py", line 105, in open_websocket
    async with trio.open_nursery() as new_nursery:
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\trio\_core\_run.py", line 815, in __aexit__
    raise combined_error_from_nursery
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\trio_websocket\_impl.py", line 1205, in _reader_task
    await handler(event)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\trio_websocket\_impl.py", line 1172, in _handle_pong_event
    event.set()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\trio\_core\_ki.py", line 159, in wrapper
    return fn(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\trio\_sync.py", line 57, in set
    _core.reschedule(task)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\trio\_core\_generated_run.py", line 100, in reschedule
    return GLOBAL_RUN_CONTEXT.runner.reschedule(task, next_send)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\trio\_core\_run.py", line 1407, in reschedule
    assert task._runner is self
AssertionError
Exception in thread Thread-8 (master_the_pool):
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\trio\_timeouts.py", line 106, in fail_at
    yield scope
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\blocknative\stream.py", line 281, in _heartbeat
    await self._ws.ping()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\trio_websocket\_impl.py", line 906, in ping
    await event.wait()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\trio\_sync.py", line 76, in wait
    await _core.wait_task_rescheduled(abort_fn)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\trio\_core\_traps.py", line 166, in wait_task_rescheduled
    return (await _async_yield(WaitTaskRescheduled(abort_func))).unwrap()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\outcome\_impl.py", line 138, in unwrap
    raise captured_error
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\trio\_core\_run.py", line 1172, in raise_cancel
    raise Cancelled._create()
trio.Cancelled: Cancelled

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "c:\NFT\revealBot\txpool_master.py", line 107, in master_the_pool
    stream.connect()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\blocknative\stream.py", line 165, in connect
    return trio.run(self._connect, base_url)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\trio\_core\_run.py", line 1932, in run
    raise runner.main_task_outcome.error
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\blocknative\stream.py", line 322, in _connect
    await self._handle_connection(base_url)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\blocknative\stream.py", line 309, in _handle_connection
    async with trio.open_nursery() as nursery:
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\trio\_core\_run.py", line 815, in __aexit__
    raise combined_error_from_nursery
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\blocknative\stream.py", line 280, in _heartbeat
    with trio.fail_after(PING_TIMEOUT):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\trio\_timeouts.py", line 108, in fail_at
    raise TooSlowError
trio.TooSlowError
```

### Python Version

python310

**Comment by asafd11** [comment]
will this work  ?
while True:
    try:
        stream.connect()
    except:
        print('disconnected txpool')
        continue

will it keep the sub and filters or do i have to reapply the subs?

**Comment by taylorjdawson** [comment]
@asafd11 Did you try the above implementation and find that it worked? 

Also take a look at this method [here](https://github.com/blocknative/python-sdk/blob/d56d1ac726c6152b2f12af8f477dcfe24558f6ac/blocknative/stream.py#L264-L282):

```python
async def _heartbeat(self):
    """Send periodic pings on WebSocket.

    Wait up to ``PING_TIMEOUT`` seconds to send a ping and receive a pong. Raises
    ``TooSlowError`` if the timeout is exceeded. If a pong is received, then
    wait ``PING_INTERVAL`` seconds before sending the next ping.

    Note:
        This function runs until cancelled.

    Raises:
        ConnectionClosed: if websocket is closed.
        TooSlowError: if the timeout expires.
    """


    while True:
        with trio.fail_after(PING_TIMEOUT):
            await self._ws.ping()
        await trio.sleep(PING_INTERVAL)
```

https://trio.readthedocs.io/en/stable/reference-core.html?highlight=fail_after#trio.fail_after

It means that a pong was not received within the given timeout period which is set to 10 seconds.

**Comment by taylorjdawson** [comment]
@asafd11 Closing for now please feel free to reopen if issue exists! 👍🏾
