### ISSUE TITLE
[Bug]: ERROR:root:Handshake failed at Windows

### ISSUE THREAD

**Issue by jiangdydy** [blocknative/python-sdk#40]
### Current Behavior

I can run my code at linux.But it was wrong at windows.

### Expected Behavior

I want to run my python code at windows

### Steps To Reproduce

from blocknative.stream import Stream
import json
stream = Stream('')
# Define your transaction handler
async def txn_handler(txn, unsubscribe):
    pass
    # if txn['status'] == "confirmed":
    #     # Output the transaction data to the console
    #     print(json.dumps(txn, indent=4))
    #
    #     # Unsubscribe from this subscription
    #     unsubscribe()

# Define the address you want to watch
try:
    uniswap_v2_address = ''
    # Register the subscription
    stream.subscribe_address(uniswap_v2_address, txn_handler)

    # Start the websocket connection and start receiving events!
    stream.connect()
except Exception as e:
    print(f'{e}')

### Python Version

python3.9

### Relevant log output

```shell
ERROR:root:Handshake failed
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\Tron\lib\site-packages\blocknative\stream.py", line 320, in _connect
    async with open_websocket_url(base_url) as ws:
  File "C:\ProgramData\Anaconda3\envs\Tron\lib\site-packages\async_generator\_util.py", line 34, in __aenter__
    return await self._agen.asend(None)
  File "C:\ProgramData\Anaconda3\envs\Tron\lib\site-packages\async_generator\_impl.py", line 366, in step
    return await ANextIter(self._it, start_fn, *args)
  File "C:\ProgramData\Anaconda3\envs\Tron\lib\site-packages\async_generator\_impl.py", line 202, in send
    return self._invoke(self._it.send, value)
  File "C:\ProgramData\Anaconda3\envs\Tron\lib\site-packages\async_generator\_impl.py", line 209, in _invoke
    result = fn(*args)
  File "C:\ProgramData\Anaconda3\envs\Tron\lib\site-packages\trio_websocket\_impl.py", line 124, in open_websocket
    raise DisconnectionTimeout from None
  File "C:\ProgramData\Anaconda3\envs\Tron\lib\site-packages\trio\_core\_run.py", line 815, in __aexit__
    raise combined_error_from_nursery
  File "C:\ProgramData\Anaconda3\envs\Tron\lib\site-packages\trio_websocket\_impl.py", line 1205, in _reader_task
    await handler(event)
  File "C:\ProgramData\Anaconda3\envs\Tron\lib\site-packages\trio_websocket\_impl.py", line 1082, in _handle_reject_data_event
    raise ConnectionRejected(self._reject_status, self._reject_headers,
trio_websocket._impl.ConnectionRejected
```

**Comment by 137996047** [comment]
Has this problem been solved?

**Comment by taylorjdawson** [comment]
@137996047 @jiangdydy are you still experiencing an issue here? I was never able to repro so if you could provide repro steps that would be great!

**Comment by taylorjdawson** [comment]
@137996047 @jiangdydy Ping :)

**Comment by jiangdydy** [comment]
@taylorjdawson  I still can not use this python-sdk of blocknative.
Even very simple code can fail under Windows OS.
